Check for the debchange executable in the PATH
The executable's package (devscripts) is not installed by default on
GitHub Actions (GHA) runner images. Hence, there should be a check that
it can be found in the PATH.

diff --git a/scripts/sync-upstream b/scripts/sync-upstream
--- a/scripts/sync-upstream
+++ b/scripts/sync-upstream
@@ -41,6 +41,11 @@ if ! [ "$(command -v git)" ]; then
     exit 1
 fi
 
+if ! [ "$(command -v debchange)" ]; then
+    printf "%s: %s\n" "${PROGNAME}" "debchange cannot be found in the PATH!" >&2
+    exit 1
+fi
+
 if ! [ "$(command -v pcre2grep)" ]; then
     printf "%s: %s\n" "${PROGNAME}" "pcre2grep cannot be found in the PATH!" >&2
     exit 1
